# Server configuration
server.port=8082
spring.application.name=notification-service

# Eureka Client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true





# JPA/Hibernate properties

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Dashboard service URL (for service-to-service communication)
dashboard.service.url=http://dashboard-service:8089

spring.datasource.url=jdbc:mysql://localhost:3306/operation
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# Logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.error.include-message=always
server.error.include-binding-errors=always


# Configuration SSL explicite

# Configuration Gmail SMTP complète
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nadanefzi22@gmail.com
spring.mail.password=Nada879nefzi  # Doit être un mot de passe d'application
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
