package com.example.dashboard_service.model;

public enum SpecialiteAnesthesiste {
    ANESTHESIE_CARDIOTHORACIQUE,
    ANESTHESIE_SOINS_CRITIQUES,
    ANESTHESIE_NEUROCHIRURGICALE,
    ANESTHESIE_OBSTETRICALE,
    ANESTHESIE_ORTHOPEDIQUE,
    ANESTHESIE_PEDIATRIQUE,
    ANESTHESIE_PALLIATIVE,
    ANESTHESIE_GENERALE
}
